-- MySQL Script generated by MySQL Workbench
-- Wed Sep 11 10:53:07 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `esportdata` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `esportdata` DEFAULT CHARACTER SET utf8 ;
USE `esportdata` ;

-- -----------------------------------------------------
-- Table `mydb`.`t_tournament`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esportdata`.`t_tournament` ;

CREATE TABLE IF NOT EXISTS `esportdata`.`t_tournament` (
  `id` BIGINT NOT NULL,
  `tournament_name` VARCHAR(60) NULL,
  `starting_date` DATE NULL,
  `ending_date` DATE NULL,
  `game` VARCHAR(255) NULL,
  `organizer` VARCHAR(255) NULL,
  `city` VARCHAR(255) NULL,
  `prize_pool` DOUBLE NULL,
  `online` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tournament_name_UNIQUE` (`tournament_name` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
